app:
  log_level: "info"
  host: "0.0.0.0"
  port: 8080

database:
  host: "postgres"
  port: 5432
  user: "testuser"
  password: "testpassword"
  database_name: "escape"
  schema_name: "account"
  ssl_mode: "disable"

auth:
  jwt_secret: ""  # Set via GATEWAY_AUTH_JWT_SECRET environment variable    