// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package mysql

import (
	"database/sql"
	"time"
)

type RefreshToken struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type User struct {
	ID           int64        `json:"id"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}
