version: "2"
sql: 
  - schema: "../../../db/migrations/000001_init_account.up.sql"
    queries: "query.sql"
    engine: "mysql"
    gen:
      go:
        package: "mysql"
        out: "mysql"
        emit_json_tags: true